Add parameters `$useBootstrap`, `$checkEvents` and `$configGroupPostfix` to the `HttpApplicationRunner`
yiisoft/yii-runner-http pull request #43
Opened 2023-01-19 14:59 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  |

2023-01-20 21:14 UTC, samdark requested changes
README should be updated.

2023-02-02 17:56 UTC, samdark commented on README.md
> +By default, HTTP runner .
?

2023-02-02 18:01 UTC, samdark requested changes

2023-02-02 18:01 UTC, samdark commented on src/HttpApplicationRunner.php
> +     * @param array $nestedEventsGroups Configuration group names that included to events' configuration group. This is
```suggestion
     * @param array $nestedEventsGroups Configuration group names that included into events' configuration group. This is
```

2023-02-02 18:01 UTC, samdark commented on src/HttpApplicationRunner.php
> +     * needed for reverse and recursive merge events' configurations.
```suggestion
     * needed for reverse and recursive merge of events' configurations.
```

2023-02-04 10:08 UTC, vjik commented on README.md
> +By default, HTTP runner .
fixed

2023-02-04 10:08 UTC, vjik commented on src/HttpApplicationRunner.php
> +     * @param string $paramsGroup The config parameters group name.
done

2023-02-04 10:08 UTC, vjik commented on src/HttpApplicationRunner.php
> +     * @param bool $checkEvents Whether check events' configuration.
done

2023-02-04 10:08 UTC, vjik commented on src/HttpApplicationRunner.php
> +     * @param array $nestedParamsGroups Configuration group names that included to config parameters group. This is
done

2023-02-04 10:08 UTC, vjik commented on src/HttpApplicationRunner.php
> +     * @param array $nestedEventsGroups Configuration group names that included to events' configuration group. This is
done

2023-02-04 10:08 UTC, vjik commented on src/HttpApplicationRunner.php
> +     * needed for reverse and recursive merge events' configurations.
done

2023-02-04 10:09 UTC, vjik commented on src/HttpApplicationRunner.php
> +     * needed for recursive merge parameters.
done

2023-02-05 08:20 UTC, samdark approved these changes

2023-02-05 08:20 UTC, samdark commented on README.md
> +`$nestedParamsGroups` — configuration group names that included to config parameters group. This is needed for recursive
```suggestion
`$nestedParamsGroups` — configuration group names that are included into config parameters group. This is needed for recursive
```

2023-02-05 08:20 UTC, samdark commented on README.md
> +`$nestedEventsGroups` — configuration group names that included to events' configuration group. This is needed for
```suggestion
`$nestedEventsGroups` — configuration group names that are included into events' configuration group. This is needed for 
```

2023-02-05 08:20 UTC, samdark commented on src/HttpApplicationRunner.php
> +     * @param array $nestedParamsGroups Configuration group names that included into configuration parameters group.
```suggestion
     * @param array $nestedParamsGroups Configuration group names that are included into configuration parameters group.
```

2023-02-05 08:20 UTC, samdark commented on src/HttpApplicationRunner.php
> +     * @param array $nestedEventsGroups Configuration group names that included into events' configuration group. This
```suggestion
     * @param array $nestedEventsGroups Configuration group names that are included into events' configuration group. This
```

2023-02-19 10:40 UTC, merged