Support stream output
yiisoft/yii-runner-http pull request #50
Opened 2023-06-09 21:01 UTC by xepozz

Implements https://github.com/yiisoft/yii-dev-panel/issues/13
Related https://github.com/yiisoft/yii-debug-api/pull/117

2023-06-10 12:56 UTC, vjik reviewed
Tests is fail... and need tests for new code.

2023-06-10 15:13 UTC, samdark approved these changes
Need a CHANGELOG line + fixing tests.

2023-06-11 17:36 UTC, vjik requested changes
Need changelog

2023-06-11 17:36 UTC, vjik commented on src/SapiEmitter.php
> +                ob_end_flush();
[Seems](https://app.codecov.io/gh/yiisoft/yii-runner-http/pull/50/blob/src/SapiEmitter.php#L121), it's not covered by tests.

2023-07-10 15:10 UTC, samdark approved these changes

2023-07-10 15:11 UTC, merged

2023-07-10 15:11 UTC, samdark commented
👍